name: Build

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir -p build
          sudo ./build.sh

      # Upload
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          path: build/*am62xx-evm*.tar.xz
          name: am62xx-evm-artifacts
          if-no-files-found: error

      # Upload
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          path: build/bsp_sources.tar.xz
          name: bsp_sources_common
          if-no-files-found: error

