name: Build

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install -y \
              pigz expect pv \
              binfmtc binfmt-support \
              qemu-user qemu-user-static qemu-system-arm \
              debian-archive-keyring bdebstrap \
              build-essential autoconf automake \
              bison flex libssl-dev \
              bc u-boot-tools swig python3-pyelftools \
              gcc-aarch64-linux-gnu
          sudo apt install --fix-broken

      - name: Build
        run: |
          mkdir -p build
          sudo ./build.sh

      - name: Upload AM62x artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          path: build/*am62xx-evm*
          name: am62xx-evm-artifacts
          if-no-files-found: error

      - name: Upload BSP Sources package
        uses: actions/upload-artifact@v3.1.2
        with:
          path: build/bsp_sources.tar.xz
          name: bsp_sources_common
          if-no-files-found: error

